package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DrinkWaterServerImplService service = new DrinkWaterServerImplService();
 * DrinkWaterIface portType = service.getDrinkWaterServerImplPort();
 * portType.findDrinkWater(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DrinkWaterServerImplService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.194.172.10:8081/bzyj/services/findDrinkWater?wsdl")
public class DrinkWaterServerImplService extends Service {

	private final static URL DRINKWATERSERVERIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.tempuri.DrinkWaterServerImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.DrinkWaterServerImplService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.194.172.10:8081/bzyj/services/findDrinkWater?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.194.172.10:8081/bzyj/services/findDrinkWater?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DRINKWATERSERVERIMPLSERVICE_WSDL_LOCATION = url;
	}

	public DrinkWaterServerImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DrinkWaterServerImplService() {
		super(DRINKWATERSERVERIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://tempuri.org/", "DrinkWaterServerImplService"));
	}

	/**
	 * 
	 * @return returns DrinkWaterIface
	 */
	@WebEndpoint(name = "DrinkWaterServerImplPort")
	public DrinkWaterIface getDrinkWaterServerImplPort() {
		return super.getPort(new QName("http://tempuri.org/",
				"DrinkWaterServerImplPort"), DrinkWaterIface.class);
	}

}
