package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RadiationStationListIface", targetNamespace = "http://iface.server.webservice.zkyt.com")
public interface RadiationStationListIface {

	/**
	 * 
	 * @param areaCode
	 * @param name
	 * @param cityCode
	 * @param baseNum
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getRadiationStationList", targetNamespace = "http://iface.server.webservice.zkyt.com", className = "com.zkyt.webservice.server.iface.GetRadiationStationList")
	@ResponseWrapper(localName = "getRadiationStationListResponse", targetNamespace = "http://iface.server.webservice.zkyt.com", className = "com.zkyt.webservice.server.iface.GetRadiationStationListResponse")
	public String getRadiationStationList(
			@WebParam(name = "name", targetNamespace = "") String name,
			@WebParam(name = "cityCode", targetNamespace = "") String cityCode,
			@WebParam(name = "areaCode", targetNamespace = "") String areaCode,
			@WebParam(name = "baseNum", targetNamespace = "") String baseNum);

}
