package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RadiationStationListImplService service = new RadiationStationListImplService();
 * RadiationStationListIface portType = service.getRadiationStationListImplPort();
 * portType.getRadiationStationList(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RadiationStationListImplService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.194.172.10:8081/bzyj/services/getRadiationStation?wsdl")
public class RadiationStationListImplService extends Service {

	private final static URL RADIATIONSTATIONLISTIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.tempuri.RadiationStationListImplService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.RadiationStationListImplService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.194.172.10:8081/bzyj/services/getRadiationStation?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.194.172.10:8081/bzyj/services/getRadiationStation?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RADIATIONSTATIONLISTIMPLSERVICE_WSDL_LOCATION = url;
	}

	public RadiationStationListImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RadiationStationListImplService() {
		super(RADIATIONSTATIONLISTIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://tempuri.org/", "RadiationStationListImplService"));
	}

	/**
	 * 
	 * @return returns RadiationStationListIface
	 */
	@WebEndpoint(name = "RadiationStationListImplPort")
	public RadiationStationListIface getRadiationStationListImplPort() {
		return super.getPort(new QName("http://tempuri.org/",
				"RadiationStationListImplPort"),
				RadiationStationListIface.class);
	}

}
